apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: roboshop-dev
    region: us-east-1
managedNodeGroups:
  - name: roboshop-dev
    instanceTypes:
      - t3.micro
      - t3.small
      - c7i-flex.large
      - m7i-flex.large  
    desiredCapacity: 6 #  by default this value is 3
    spot: false